加了个依赖
RimoChan/Librian pull request #10
Opened 2019-10-09 14:10 UTC by BeautyYuYanli

2019-10-09 17:30 UTC, RimoChan requested changes
現在它似乎不依賴pathlib2，只是用了標準庫的pathlib吧？

2019-10-10 04:09 UTC, BeautyYuYanli commented
咦我安装依赖的时候报错了

2019-10-10 04:09 UTC, BeautyYuYanli commented
是wxpython依赖它来着

2019-10-10 04:17 UTC, RimoChan commented
嗯……我的wx沒有這個依賴？
你再確認一下？

2019-10-10 04:24 UTC, BeautyYuYanli commented
```
$ pip uninstall pathlib2       

Uninstalling pathlib2-2.3.5:
  Would remove:
    /home/beautyyu/.local/lib/python3.7/site-packages/pathlib2-2.3.5.dist-info/*
    /home/beautyyu/.local/lib/python3.7/site-packages/pathlib2/*
Proceed (y/n)? y
  Successfully uninstalled pathlib2-2.3.5

$ pip install --user wxpython  

Collecting wxpython
  Using cached https://files.pythonhosted.org/packages/9a/a1/9c081e04798eb134b63def3db121a6e4436e1d84e76692503deef8e75423/wxPython-4.0.6.tar.gz
Requirement already satisfied: numpy in /home/beautyyu/.local/lib/python3.7/site-packages (from wxpython) (1.15.1)
Requirement already satisfied: pillow in /usr/lib/python3.7/site-packages (from wxpython) (6.1.0)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from wxpython) (1.12.0)
Installing collected packages: wxpython
  Running setup.py install for wxpython ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-avy0dec2/wxpython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-80sa7laq/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.
    
    "/usr/bin/python" -u build.py build
    Traceback (most recent call last):
      File "build.py", line 30, in <module>
        import pathlib2
    ModuleNotFoundError: No module named 'pathlib2'
    Command '"/usr/bin/python" -u build.py build' failed with exit code 1.
```

2019-10-10 04:44 UTC, RimoChan commented
不同系統居然不一樣，還有wx不把pathlib2作依賴有問題的吧……

2019-10-10 04:45 UTC, merged